services:
  demanio:
    image: ${DOCKER_REGISTRY-}demanio
    build:
      context: .
      dockerfile: Demanio/Dockerfile
      target: ${BUILD_TARGET:-final}
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      #ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/https-dev-cert.pfx"
      #ASPNETCORE_Kestrel__Endpoints__Https__Certificate__Password: ${HTTPS_CERT_PASSWORD:-myCertPassword}
    # volumes:
    #   - ./https/https-dev-cert.pfx:/https/https-dev-cert.pfx:ro
    ports:
        - "8080:8080"
       # - "443:443"